# Generated by Django 2.2.4 on 2019-08-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='decs',
            new_name='desc',
        ),
    ]
